// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

import {DataTypes, Model, Sequelize} from "sequelize";

export class Owners extends Model {
  public id!: number;
  public name!: string;

  public static associate(models) {
    Owners.hasMany(models.articles, {
      foreignKey: {
        name: 'ownerIdKey',
        field: 'owner_id',
      },
      as: 'articles',
    });
  }
}

export default function(sequelize: Sequelize, dataTypes: typeof DataTypes): typeof Model {
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-mode

  Owners.init({
    id: {
      type: dataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: new dataTypes.STRING(128),
      allowNull: true,
    },
  },{
    tableName: 'owners',
    underscored: true,
    modelName: 'owners',
    timestamps: false,
    sequelize,
  });

  return Owners;
}
